channels:
  - conda-forge
dependencies:
  - python=3.10 
  - pip
  - pip:
    - fastapi
    - pydantic
    - openai >=1.25.1
    - anthropic
    - tiktoken
    - aiohttp
    - aiofiles
    - mistralai
    - huggingface-hub
    - weave
    - spacy
    - confection
    - vllm
    - transformers
    - fschat
    - ray
    - openai>=1.25.1
    - anthropic
    - mistralai
    - google-generativeai
    - google-cloud-aiplatform
    - torchvision
    - sentence_transformers
    - matplotlib
    - accelerate
    - datasketch
    - pandas
    - art
    - tenacity
    - boto3
    - bpe